/**
 * TestTypeCheck Hook Types
 * Generated by Atomix CLI
 */

/**
 * Component State Interface
 */
export interface ComponentState {
  isActive: boolean;
  isHovered: boolean;
  isFocused: boolean;
  isLoading: boolean;
  variant: 'primary' | 'secondary' | 'outline' | string;
  size: 'sm' | 'md' | 'lg' | string;
}

/**
 * Event Handler Types
 */
export type ClickHandler = (event: React.MouseEvent<HTMLDivElement>) => void;
export type HoverHandler = (event: React.MouseEvent<HTMLDivElement>) => void;
export type FocusHandler = (event: React.FocusEvent<HTMLDivElement>) => void;
export type BlurHandler = (event: React.FocusEvent<HTMLDivElement>) => void;
export type StateChangeHandler = (state: ComponentState) => void;

/**
 * Variant Configuration
 */
export type VariantType = 'primary' | 'secondary' | 'outline' | 'ghost' | 'link';

/**
 * Size Configuration  
 */
export type SizeType = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

/**
 * Glass Effect Configuration
 */
export interface GlassConfig {
  displacementScale?: number;
  blurAmount?: number;
  saturation?: number;
  elasticity?: number;
}
