import { defineConfig } from 'rollup';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { terser } from '@rollup/plugin-terser';
import { babel } from '@rollup/plugin-babel';
import shebang from 'rollup-plugin-preserve-shebangs';

/**
 * Rollup configuration for bundling Atomix CLI
 * Creates a self-contained CLI executable with bundled dependencies
 */

export default defineConfig({
  input: 'scripts/atomix-cli.js',
  
  output: [
    {
      file: 'dist/cli.js',
      format: 'cjs',
      sourcemap: true,
      exports: 'auto',
      banner: '#!/usr/bin/env node\n// Atomix CLI - Bundled Distribution',
      footer: '// Generated by Rollup'
    }
  ],
  
  plugins: [
    // Preserve shebang for executable scripts
    shebang.preserveShebangs(),
    
    // Convert CommonJS modules to ES6
    commonjs({
      include: 'node_modules/**',
      extensions: ['.js'],
      ignoreGlobal: false,
      sourceMap: false
    }),
    
    // Resolve node_modules
    resolve({
      preferBuiltins: true,
      browser: false,
      extensions: ['.js', '.json'],
      mainFields: ['main', 'module']
    }),
    
    // Handle JSON files
    json({
      compact: true,
      namedExports: true
    }),
    
    // Transpile with Babel
    babel({
      babelHelpers: 'bundled',
      exclude: 'node_modules/core-js/**',
      presets: [
        ['@babel/preset-env', {
          targets: {
            node: '18'
          },
          useBuiltIns: 'usage',
          corejs: 3
        }]
      ],
      plugins: [
        '@babel/plugin-transform-runtime'
      ]
    }),
    
    // Minify for production
    terser({
      compress: {
        drop_console: false, // Keep console logs for CLI
        drop_debugger: true,
        passes: 2
      },
      mangle: {
        keep_fnames: true, // Keep function names for better stack traces
        reserved: ['AtomixCLIError', 'ValidationError'] // Preserve important class names
      },
      format: {
        comments: false,
        preamble: '/* Atomix CLI Bundle */'
      }
    })
  ],
  
  // External dependencies that should remain external
  external: [
    // Built-in Node.js modules
    'fs',
    'fs/promises',
    'path',
    'process',
    'os',
    'util',
    'events',
    'stream',
    'child_process',
    'crypto',
    'url',
    'assert',
    
    // Large modules better left as external dependencies
    'typescript', // Very large, installed separately
    'sass',       // Native bindings, difficult to bundle
    'postcss'     // Large ecosystem, better as peer dep
  ],
  
  // Treeshaking configuration
  treeshake: {
    moduleSideEffects: (id) => {
      // Keep side effects for CLI entry point and configuration files
      if (id.includes('atomix-cli.js') || id.includes('config')) {
        return true;
      }
      // Remove side effects from most dependencies
      return false;
    },
    propertyReadSideEffects: false,
    unknownGlobalSideEffects: false
  }
});

/**
 * Alternative configuration for development (unminified)
 */
export const developmentConfig = defineConfig({
  ...defineConfig()[0],
  output: [
    {
      file: 'dist/cli.dev.js',
      format: 'cjs',
      sourcemap: true,
      exports: 'auto',
      banner: '#!/usr/bin/env node\n// Atomix CLI - Development Build'
    }
  ],
  plugins: defineConfig()[0].plugins.filter(plugin => 
    plugin.name !== 'terser' // Remove minification for development
  )
});

/**
 * Configuration for CLI utilities (separate bundle)
 */
export const utilitiesConfig = defineConfig({
  input: [
    'scripts/cli/utils.js',
    'scripts/cli/component-generator.js',
    'scripts/cli/token-manager.js'
  ],
  
  output: {
    dir: 'dist/cli-utils',
    format: 'cjs',
    sourcemap: true,
    chunkFileNames: '[name]-[hash].js'
  },
  
  plugins: [
    resolve({
      preferBuiltins: true
    }),
    commonjs(),
    json()
  ],
  
  external: [
    'fs',
    'fs/promises', 
    'path',
    'process'
  ]
});
